name: corn_farming
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  lottie: ^3.1.3
  get: ^4.7.2
  shared_preferences: ^2.3.3
  auto_size_text: ^3.0.0
  google_fonts: ^6.2.1
  fluttertoast: ^8.2.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"

flutter_native_splash:
  android: true
  ios: true
  color: "#FEF3E5"
  color_dark: "#332828"
  image: assets/images/splash_android.png
  branding: assets/images/branding_desk.png
  branding_bottom_padding_ios: 90

  android_12:
    color: "#FEF3E5"
    color_dark: "#332828"
    image: assets/images/splash_android.png
    branding: assets/images/branding.png
    icon_background_color: "#FEF3E5"
    fullscreen: true
    branding_bottom_padding: 190


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lottie/
    - assets/language/
